# Generated by Django 4.0.2 on 2022-04-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.PositiveIntegerField(default=18, max_length=150),
        ),
    ]
