# Generated by Django 4.0.2 on 2022-04-30 15:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0006_kategorie_ogloszenie'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Murarz', 'Murarz'), ('Glazurnik', 'Glazurnik'), ('Elektryk', 'Elektryk'), ('Slusarz', 'Slusarz'), ('Informatyk', 'Informatyk'), ('Pomoc domowa', 'Pomoc domowa'), ('Malarz', 'Malarz')], default='Brak', max_length=64),
        ),
    ]
