# Generated by Django 4.0.2 on 2022-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0008_worker_is_worker_alter_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
    ]
