# Generated by Django 4.0.2 on 2022-04-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0012_alter_worker_is_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='age',
        ),
    ]
