# Generated by Django 4.0.2 on 2022-04-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0013_remove_worker_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='rating',
        ),
        migrations.AddField(
            model_name='worker',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
