# Generated by Django 4.0.2 on 2022-05-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0014_remove_worker_rating_worker_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='categories',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='Image',
            new_name='image',
        ),
    ]
