# Generated by Django 4.0.2 on 2022-05-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0015_rename_categories_worker_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='categorie',
        ),
    ]
