# Generated by Django 4.0.2 on 2022-05-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0016_remove_worker_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategorie',
            old_name='tytul',
            new_name='nazwa',
        ),
        migrations.AddField(
            model_name='worker',
            name='category',
            field=models.CharField(default='brak', max_length=128),
        ),
    ]
