# Generated by Django 4.0.2 on 2022-05-02 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fachowiecApi', '0017_rename_tytul_kategorie_nazwa_worker_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='Pracownik',
        ),
    ]
