# Generated by Django 4.0.2 on 2022-05-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0018_rename_worker_pracownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='category',
            field=models.CharField(blank=True, default='brak', max_length=128, null=True),
        ),
    ]
