# Generated by Django 4.0.2 on 2022-05-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0019_alter_pracownik_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
