# Generated by Django 4.0.2 on 2022-05-05 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fachowiecApi', '0020_pracownik_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='category',
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='is_worker',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workerUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
