# Generated by Django 4.0.2 on 2022-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0027_remove_fachowiec_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='category',
            field=models.TextField(choices=[('Murarz', 'Murarz'), ('Glazurnik', 'Glazurnik'), ('Elektryk', 'Elektryk'), ('Slusarz', 'Slusarz'), ('Informatyk', 'Informatyk'), ('Pomoc domowa', 'Pomoc domowa'), ('Malarz', 'Malarz')], default='brak', max_length=64),
        ),
    ]
