# Generated by Django 4.0.2 on 2022-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0028_ogloszenie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogloszenie',
            name='category',
            field=models.TextField(default='brak', max_length=124),
        ),
    ]
