# Generated by Django 4.0.2 on 2022-05-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0030_ogloszenie_image_ogloszenie_phone_ogloszenie_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogloszenie',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ogloszenie',
            name='town',
            field=models.TextField(max_length=64),
        ),
    ]
