# Generated by Django 4.0.2 on 2022-05-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0031_alter_ogloszenie_phone_alter_ogloszenie_town'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogloszenie',
            old_name='Tytul',
            new_name='tytul',
        ),
    ]
