# Generated by Django 4.0.2 on 2022-05-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0032_rename_tytul_ogloszenie_tytul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogloszenie',
            name='image',
        ),
    ]
