# Generated by Django 4.0.2 on 2022-05-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0033_remove_ogloszenie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='opis',
            field=models.TextField(default='brak'),
        ),
    ]
