# Generated by Django 4.0.2 on 2022-06-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0041_alter_ogloszenie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
