# Generated by Django 4.0.2 on 2022-06-08 15:27

from django.db import migrations, models
import fachowiecApi.models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0042_ogloszenie_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogloszenie',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=fachowiecApi.models.upload_announcement_image),
        ),
    ]
