# Generated by Django 4.0.2 on 2022-06-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0043_ogloszenie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miejscowosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=254)),
            ],
        ),
    ]
