# Generated by Django 4.0.2 on 2022-06-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0044_miejscowosci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miejscowosci',
            old_name='miejscowosc',
            new_name='town',
        ),
    ]
