# Generated by Django 4.0.2 on 2022-07-07 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0045_rename_miejscowosc_miejscowosci_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fachowiec',
            name='rating',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
