# Generated by Django 4.0.2 on 2022-07-10 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0048_rating_commentvalue_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fachowiec',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
