# Generated by Django 4.0.2 on 2022-07-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0049_alter_fachowiec_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='commentedBy',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
