# Generated by Django 4.0.2 on 2022-07-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0055_remove_fachowiec_rating_rating_pracownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='pracownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fachowiecApi.fachowiec'),
        ),
    ]
