# Generated by Django 4.0.2 on 2022-07-14 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0058_remove_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='pracownik',
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userCommented', to='fachowiecApi.fachowiec'),
        ),
    ]
