# Generated by Django 4.0.2 on 2022-07-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0060_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='commentedByusername',
            field=models.CharField(default='Anonymous', max_length=64),
        ),
    ]
