# Generated by Django 4.0.2 on 2022-07-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0061_rating_commentedbyusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='userUsername',
            field=models.CharField(default='', max_length=128),
        ),
    ]
