# Generated by Django 4.0.2 on 2022-07-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachowiecApi', '0062_rating_userusername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='userUsername',
        ),
        migrations.AlterField(
            model_name='rating',
            name='commentedByusername',
            field=models.CharField(blank=True, default='Anonymous', max_length=64, null=True),
        ),
    ]
